image: ubuntu

install:
  - nvm use 9.11.2
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off

environment:
  FTP_HOST: ftp.dlptest.com
  FTP_USER: dlpuser@dlptest.com
  FTP_PASS: 3D6XZV9MKdhM5fF
  FTP_PORT: 21
