name: Node.js tests
on:
  - push
  - pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
        env:
          GCS_KEY: ${{secrets.GCS_KEY}}
          S3_KEY: ${{secrets.S3_KEY}}
          S3_SECRET: ${{secrets.S3_SECRET}}
          S3_ENDPOINT: ${{secrets.S3_ENDPOINT}}
          S3_BUCKET: ${{secrets.S3_BUCKET}}
          S3_REGION: ${{secrets.S3_REGION}}
